server {
    listen 8080;
    server_name ${FRAPPE_SITE_NAME_HEADER};

    client_max_body_size ${CLIENT_MAX_BODY_SIZE};

    location /assets/ {
        alias /home/frappe/frappe-bench/sites/assets/;
        access_log off;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location /files/ {
        alias /home/frappe/frappe-bench/sites/${FRAPPE_SITE_NAME}/public/files/;
        expires 1h;
    }

    location /private/ {
        internal;
        alias /home/frappe/frappe-bench/sites/${FRAPPE_SITE_NAME}/private/;
    }

    location /socket.io {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host ${FRAPPE_SITE_NAME_HEADER};
        proxy_set_header X-Frappe-Site-Name ${FRAPPE_SITE_NAME_HEADER};
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://${SOCKETIO};
    }

    location / {
        proxy_http_version 1.1;
        proxy_set_header Host ${FRAPPE_SITE_NAME_HEADER};
        proxy_set_header X-Frappe-Site-Name ${FRAPPE_SITE_NAME_HEADER};
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout ${PROXY_READ_TIMEOUT}s;
        proxy_pass http://${BACKEND};
    }
}
